### ISSUE TITLE
添加paypal支付出错

### ISSUE THREAD

**Issue by YinBuLiao** [Tai7sy/card-gateway#10]
这是报错截图![image](https://user-images.githubusercontent.com/35324248/78354496-8606bf00-75de-11ea-843c-f00c2b2f55e7.png)
这是配置截图
![image](https://user-images.githubusercontent.com/35324248/78354548-a46cba80-75de-11ea-9813-cda6e05c2586.png)

**Comment by Tai7sy** [comment]
请输入英文引号

**Comment by YinBuLiao** [comment]
我看见了你之前回复的我直接复制了，没注意浏览器翻译了，解决了谢谢大佬
