### ISSUE TITLE
风大大，paypal配置无法填写，是为什么啊？

### ISSUE THREAD

**Issue by xinxinjiushizhu** [Tai7sy/card-gateway#11]
填写配置后，点编辑就卡住，报错
https://s1.ax1x.com/2020/04/26/Jc5s9P.png
https://s1.ax1x.com/2020/04/26/Jc56c8.png

**Comment by Tai7sy** [comment]
请自行百度谷歌json格式

**Comment by xinxinjiushizhu** [comment]
好的，谢谢风大大
