### ISSUE TITLE
添加Mugglepay支付方式的时候前台不显示

### ISSUE THREAD

**Issue by mengyalei** [Tai7sy/card-gateway#12]
搭建环境：
Nginx 1.15.9
PHP 7.1 
MySQL 5.7.19
按照教程搭建完成，修改完网站配置信息后，后台查看支付渠道时发现支付方式全部都是默认开启状态
，经过支付测试发现默认的支付方式是pay_id=4的这个。当禁用pay_id=4的这个支付方式并开启其他支付方式的时候，在支付的时候，支付跳转链接变成了pay_id=undefined。也就是说未识别新设置的其他支付方式。

**Comment by Tai7sy** [comment]
请配置前台支付方式
