### ISSUE TITLE
请问一下易支付的接口后台配置格式是什么呢？

### ISSUE THREAD

**Issue by YinBuLiao** [Tai7sy/card-gateway#14]
请问一下易支付的接口后台配置格式是什么呢？

**Comment by Tai7sy** [comment]
暂不支持

**Comment by YinBuLiao** [comment]
我看见有个Epay，不是易支付吗...

**Comment by YinBuLiao** [comment]
![image](https://user-images.githubusercontent.com/35324248/80866215-1577be80-8cc0-11ea-85f0-8d0cb6f3565a.png)
