### ISSUE TITLE
大大，如何添加微信payjs支付驱动

### ISSUE THREAD

**Issue by BOTBAKS** [Tai7sy/card-gateway#15]
求大大教一下

**Comment by Tai7sy** [comment]
驱动 Payjs
方式: 参考payjs文档里面支付方式填写(cashier/native)
配置，json格式，填写 mchid 和 key

**Comment by BOTBAKS** [comment]
![image](https://user-images.githubusercontent.com/52072126/91866192-d3c64700-eca4-11ea-936c-4c062eff5dd1.png)
大大，异步通知设置了，但是测试支付后没有反应是咋回事啊

**Comment by Tai7sy** [comment]
可以修改 .env  文件中 APP_DEBUG=true 打开调试模式
然后在storage/logs 内分析支付日志

**Comment by BOTBAKS** [comment]
大大，我是小白，看不懂。。。

**Comment by BOTBAKS** [comment]
https://i.loli.net/2020/09/03/bZolQ8BzmiWMrTw.png
大大，驱动填写cashier发起支付提示需要在客户端打开连接，我看payjs官方给了个方法可以把URL生成二维码扫描
https://i.loli.net/2020/09/03/uZoTMyq5p9ndbkY.png
但是我是纯小白，看不懂。。。

**Comment by Tai7sy** [comment]
扫码是native方法

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-gateway/commit/5bd2f66aa30b3eb9dcfc83422788ccdfb1f5177b

可以参考这里自己修改一下, cashier 改为扫码方式

**Comment by Tai7sy** [comment]
把这个文件最新版覆盖到你的 `app/Library/Gateway/Pay` 目录下

**Comment by BOTBAKS** [comment]
谢谢大大

**Comment by BOTBAKS** [comment]
https://i.loli.net/2020/09/03/oKRfru73NTexAwl.jpg(微信上跳转出来的，网页上没反应，依然是扫码页面)
大大，我覆盖后支付提示失败。。。
是不是我Payjs里面哪里设置错了
https://i.loli.net/2020/09/03/wMcBtRa6Jdnk3Q8.png

**Comment by BOTBAKS** [comment]
大大，有个问题
![image](https://user-images.githubusercontent.com/52072126/101899589-05767480-3be9-11eb-87b2-b33bbb8e2c51.png)
使用payjs微信，这里添加一个没有盾的域名后，微信支付时，网页地址会直接显示api通知地址，会直接暴露服务器IP
如果套cdn隐藏服务器IP地址，那payjs就无法 通知了，怎么办啊
