### ISSUE TITLE
大佬，帮忙看一下我的支付宝支付问题

### ISSUE THREAD

**Issue by hulu888** [Tai7sy/card-gateway#18]
配置好的支付宝当面付的appid、公钥和私钥之，进行支付测试的时候出现了下面图片中的情况，麻烦帮忙解决一下，我已经卡在这里一下午了，感谢
![image](https://user-images.githubusercontent.com/12171626/101740102-63309100-3b03-11eb-8ad2-54e6009954ed.png)

**Comment by Tai7sy** [comment]
把秘钥文件用记事本打开，中间的内容删除换行之后填进去

**Comment by hulu888** [comment]
> 把秘钥文件用记事本打开，中间的内容删除换行之后填进去

我是点的复制秘钥按钮，单独复制看了也没有换行
![image](https://user-images.githubusercontent.com/12171626/101752264-45b3f500-3b0c-11eb-9a6a-d597ef0e2b41.png)

**Comment by hulu888** [comment]
> 把秘钥文件用记事本打开，中间的内容删除换行之后填进去

关闭了几个支付方式后，又成这样了
![image](https://user-images.githubusercontent.com/12171626/101758394-3edcb080-3b13-11eb-8aa8-a3698ab92e18.png)
