### ISSUE TITLE
啥时候支持下虎皮椒，开通了个虎皮椒不会接入

### ISSUE THREAD

**Issue by 928882650** [Tai7sy/card-gateway#21]
啥时候支持下虎皮椒，开通了个虎皮椒不会接入

**Comment by 928882650** [comment]
已经解决

**Comment by Ecalose** [comment]
> 已经解决

请问下老哥是怎么解决的啊？能否发一份插件源码给我，虎皮椒那边一直没回我

**Comment by 928882650** [comment]
你应该已经解决了叭




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tai7sy/card-gateway"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 下午5:59
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Tai7sy/card-gateway] 啥时候支持下虎皮椒，开通了个虎皮椒不会接入 (#21)





  
已经解决
  
请问下老哥是怎么解决的啊？能否发一份插件源码给我，虎皮椒那边一直没回我

**Comment by Ecalose** [comment]
> 你应该已经解决了叭
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tai7sy/card-gateway" ***@***.***&gt;; 发送时间:&nbsp;2021年6月23日(星期三) 下午5:59 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [Tai7sy/card-gateway] 啥时候支持下虎皮椒，开通了个虎皮椒不会接入 (#21) 已经解决 请问下老哥是怎么解决的啊？能否发一份插件源码给我，虎皮椒那边一直没回我 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

没啊，他还是没回我
