### ISSUE TITLE
mugglepay支付失败

### ISSUE THREAD

**Issue by miaolou** [Tai7sy/card-gateway#25]
后台配置正确，测试提交订单提示：获取付款信息超时, 请刷新重试。
log文件显示：Pay.MugglePay.goPay.order, request failed {"response":null}

**Comment by Tai7sy** [comment]
说明服务器连不上支付渠道网关，请服务器上面curl试一下网络是否通畅

**Comment by bcpx** [comment]
mugglepay已经跑路了，我里面还有钱提不出来
