### ISSUE TITLE
微蓝支付添加一下吧。

### ISSUE THREAD

**Issue by lckwyaya** [Tai7sy/card-gateway#30]
微蓝支付添加一下吧。  码支付改微蓝支付 按照教程改了半天也没成功，脑壳都炸了。

**Comment by charl3s-cli** [comment]
蔚蓝那边已经有对接文件，自己配置下就好

**Comment by charl3s-cli** [comment]
> 微蓝支付添加一下吧。 码支付改微蓝支付 按照教程改了半天也没成功，脑壳都炸了。

蔚蓝那边已经有对接文件，自己配置下就好，

要是改码支付，只用把接口域名改带微蓝就可以
