### ISSUE TITLE
求对接一波v免签

### ISSUE THREAD

**Issue by RWh1te0** [Tai7sy/card-gateway#31]
VPay就是借鉴V免签写出来的，但是一开始部署了V免签且觉得VPay做的没有V免签好，所以想求风大对接一下：
[https://github.com/szvone/vmqphp](https://github.com/szvone/vmqphp)

其实我也尝试了手动改您的VPay网关，但是很遗憾失败了，我无论怎么更改代码，POST过去的数据都是空的

**Comment by RyanXu2003** [comment]
另外，vpay的网关貌似也是存在bug的，宝塔这边查不到网关post过去的数据
![nginx日志](https://images.gitee.com/uploads/images/2021/0825/220012_9b0f523a_2347240.png "屏幕截图 2021-08-25 215830.png")

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-gateway/blob/master/Pay/VPay
