### ISSUE TITLE
VPay

### ISSUE THREAD

**Issue by ldkiss** [Tai7sy/card-gateway#35]
VPay支付页面一直提示签名失败

**Comment by ldkiss** [comment]
VPay支付页面一直提示签名校检失败

**Comment by Tai7sy** [comment]
自己检查id和key填的对不对

**Comment by ldkiss** [comment]
> 自己检查id和key填的对不对

正确的

**Comment by ldkiss** [comment]
![微信截图_20211010193347](https://user-images.githubusercontent.com/14346374/136693748-54c3cfc5-c7d6-4aaa-a51b-dc880eaf7dff.png)
支付失败！
签名校验失败

**Comment by isjing2** [comment]
我也是疯狂提示失败。。

**Comment by ldkiss** [comment]
> > ![微信截图_20211010193347](https://user-images.githubusercontent.com/14346374/136693748-54c3cfc5-c7d6-4aaa-a51b-dc880eaf7dff.png) 支付失败！ 签名校验失败
> 
> 截图看看后台配置



> > ![微信截图_20211010193347](https://user-images.githubusercontent.com/14346374/136693748-54c3cfc5-c7d6-4aaa-a51b-dc880eaf7dff.png) 支付失败！ 签名校验失败
> 
> 截图看看后台配置

![QQ截图20211011103846](https://user-images.githubusercontent.com/14346374/136725908-c521e571-2f28-417a-9a43-2159ab1a142e.png)
![QQ截图20211011104133](https://user-images.githubusercontent.com/14346374/136725919-845527e2-1f2c-4ba1-a881-3de9bfc7b16b.png)

**Comment by Tai7sy** [comment]
加q帮你看一下 19060

**Comment by Tai7sy** [comment]
加QQ 19060帮你看下
