### ISSUE TITLE
程序版本 `3.15`，使用 `EpUSDT` 支付接口。支付成功后无法跳转成功

### ISSUE THREAD

**Issue by yiqiecongjian** [Tai7sy/card-gateway#38]
@imPrk0 你好大佬，对接 EpUSDT后，支付成功后可以到账。并且提示，支付成功，跳转中。
![1681184942569](https://user-images.githubusercontent.com/51590941/231051788-bc6459b1-828a-4bfb-b26f-91772d8c246d.jpg)

但是跳转之后是，支付失败，这个界面
![fd0f6c6efed4a469f286033df4e228e](https://user-images.githubusercontent.com/51590941/231052009-2ea212e4-8efe-4f6d-9f37-063b29c64743.png)

网站后台订单记录和数据库都没有epusdt订单信息，只有在epusdt 数据库里可以看到，但是提示没有回调。epusdt  对接的电报机器人提示交易成功。

网站的支付对接，使用的是：https://github.com/Tai7sy/card-gateway/blob/master/Pay/EpUSDT/Api.php

期待回复

**Comment by imPrk0** [comment]
https://github.com/Tai7sy/card-gateway/tree/master/Pay/EpUSDT
问题已经解决，如依然有问题请重新开 issues。
