### ISSUE TITLE
请写个教程，侮辱我一下。。。

### ISSUE THREAD

**Issue by BOTBAKS** [Tai7sy/card-gateway#4]
请写个教程，侮辱我一下。。。

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/wiki/%E6%94%AF%E4%BB%98%E6%8E%A5%E5%8F%A3%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3

**Comment by jeson998** [comment]
> 请写个教程，侮辱我一下。。。

同求辱！
