### ISSUE TITLE
请问PayPal支付方式是什么？

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-gateway#6]
想加个PayPal支付。

**Comment by Tai7sy** [comment]
支付方式随便写，可以参考PayPal的文件

**Comment by zhujitop** [comment]
> 支付方式随便写，可以参考PayPal的文件

只需要修改Api.php文件，在：
`
        if (!isset($config['business'])) {
            throw new \Exception('这里改成自己的PayPal收款邮箱吗');
        }`

网站后台配置选择json就行，其他都不用改了吗？

**Comment by Tai7sy** [comment]
网站后台配置选择json填写
{"business":"你的paypal邮箱"}
