### ISSUE TITLE
请教BTC或者paypal接口 方式驱动

### ISSUE THREAD

**Issue by niu12503** [Tai7sy/card-gateway#7]
有没有再具体点的教程，谢谢大佬

**Comment by Tai7sy** [comment]
PayPal驱动 PayPal，方式随便填(没有作用)
配置里面写business你的邮箱

**Comment by Aimeelu668** [comment]
对于交易所这种业务型系统，选择钱包的时候需要考虑的问题，应该是安全的同时也需要快速的业务对接。相关业务上的难点有：安全、跨链整合、庞大的数据量、还有其他的业务需求比如生成地址、地址管理、资金管理、交易记录管理、充提币及回调等等。以优盾钱包——全球首款区块链交易所钱包对接开放平台为例，以上的难点都得到了解决，且业务上有主流语言的SDK可实现快速的对接： ①Java版 https://github.com/uduncloud/udun-sdk-java ②.Net版 https://github.com/uduncloud/udun-sdk-csharp ③Php版 https://github.com/uduncloud/udun-sdk-php 就安全而言，提供了Client-Gateway Solution（CGS）、Hareware-Gateway Solution（HGS）两套解决方案。

**Comment by Tai7sy** [comment]
@Aimeelu668 欢迎提pr
